runtime: nodejs8 

instance_class: F2

env_variables:
  ENV: "development"
  DATABASE: "mongodb://1punto5:danaleger15@ds129821.mlab.com:29821/1puntocinco"
  CLIENT_ID_NEW: "853861088301-d6pp525e5fo1sbd9l1ebv0mogs158ofk.apps.googleusercontent.com"
  CLIENT_SECRET_NEW: "iGZJzWVSVfBlT9Q6_KfRaCKp" 
